/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package office_db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rashmika
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        update_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Fname = new javax.swing.JLabel();
        Minit = new javax.swing.JLabel();
        Lname = new javax.swing.JLabel();
        Ssn = new javax.swing.JLabel();
        Bdate = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        Sex = new javax.swing.JLabel();
        Salary = new javax.swing.JLabel();
        Super_ssn = new javax.swing.JLabel();
        Dno = new javax.swing.JLabel();
        FnameText = new javax.swing.JTextField();
        LnameText = new javax.swing.JTextField();
        SsnText = new javax.swing.JTextField();
        MinitText = new javax.swing.JTextField();
        AddressText = new javax.swing.JTextField();
        SalaryText = new javax.swing.JTextField();
        Super_ssnText = new javax.swing.JTextField();
        DnoText = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        SexCombo = new javax.swing.JComboBox<>();
        BdateText = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("Employee Registration");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semibold", 1, 18))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(815, 422));

        Fname.setText("First Name");

        Minit.setText("Minit");

        Lname.setText("Last Name");

        Ssn.setText("SSN");

        Bdate.setText("Date of Birth");

        Address.setText("Address");

        Sex.setText("Sex");

        Salary.setText("Salary");

        Super_ssn.setText("Super SSN");

        Dno.setText("Department No");

        FnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameTextActionPerformed(evt);
            }
        });

        MinitText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinitTextActionPerformed(evt);
            }
        });

        Super_ssnText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Super_ssnTextActionPerformed(evt);
            }
        });

        DnoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DnoTextActionPerformed(evt);
            }
        });

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        SexCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        SexCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fname)
                            .addComponent(Minit)
                            .addComponent(Lname)
                            .addComponent(Ssn)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Bdate, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Address))
                            .addComponent(Sex)
                            .addComponent(Salary)
                            .addComponent(Super_ssn)
                            .addComponent(Dno))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MinitText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Super_ssnText, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DnoText, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SexCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SsnText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(BdateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fname))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinitText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Minit))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lname))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SsnText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ssn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Bdate)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BdateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SexCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sex))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Salary)
                    .addComponent(SalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Super_ssnText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Super_ssn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DnoText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fname", "Minit", "Lname", "Ssn", "Bdate", "Address", "Sex", "Salary", "Super_ssn", "Dno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(40);
        }

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel2.setText("Employee Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Connection con ;
       PreparedStatement insert;
    private void FnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameTextActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        String fname = FnameText.getText();
        String minit = MinitText.getText();
        String lname = LnameText.getText();
        Integer ssn = Integer.parseInt(SsnText.getText());
        Date bdate = BdateText.getDate();
        String address = AddressText.getText();
        Integer sexId = SexCombo.getSelectedIndex();
        Integer salary = Integer.parseInt(SalaryText.getText());
        String super_ssn = Super_ssnText.getText();
        Integer dno = Integer.parseInt(DnoText.getText());
        String sex;
        if( SalaryText.getText() == ""){
            super_ssn = "NULL";
            }
         if( sexId==0){
             sex = "M";
            }else{
              sex = "F";
         }
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3308/office?useSSL=false","root","");
            insert = con.prepareStatement("INSERT INTO employee (Fname,Minit,Lname,Ssn,Bdate,Address,Sex,Salary,Super_ssn,Dno) VALUES(?,?,?,?,?,?,?,?,?,?)");
            insert.setString(1, fname);
            insert.setString(2, minit);
            insert.setString(3, lname);
            insert.setInt(4, ssn);
            java.util.Date dt = bdate;
            java.sql.Date bdt = new java.sql.Date(dt.getTime());
            insert.setDate(5, bdt);
            insert.setString(6, address);
            insert.setString(7, sex);
            insert.setInt(8, salary);
            insert.setString(9, super_ssn);
            insert.setInt(10, dno);
            
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");
            
            //clear the text boxes
            FnameText.setText("");
            MinitText.setText("");
            LnameText.setText("");
            SsnText.setText("");
            BdateText.setDate(null);
            AddressText.setText("");
            MinitText.setText("");
            SalaryText.setText("");
            Super_ssnText.setText("");
            DnoText.setText("");
            
            FnameText.requestFocus();
            update_data();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void update_data(){
        int count;
            try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3308/office?useSSL=false","root","");
            insert = con.prepareStatement("SELECT * FROM employee");
            ResultSet results = insert.executeQuery();
            
            ResultSetMetaData resultsData = results.getMetaData();
            count = resultsData.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
            df.setRowCount(0);
            while (results.next()) {
                Vector v = new Vector();
           
                for (int i = 0; i <= count; i++) {
                    v.add(results.getString("Fname"));
                    v.add(results.getString("Minit"));
                    v.add(results.getString("Lname"));
                    v.add(results.getInt("Ssn"));
                    v.add(results.getString("Bdate"));
                    v.add(results.getString("Address"));
                    v.add(results.getString("Sex"));
                    v.add(results.getInt("Salary"));
                    v.add(results.getString("Super_ssn"));
                    v.add(results.getInt("Dno"));
                }
                df.addRow(v);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
            try {   
                
            String fname = FnameText.getText();
            String minit = MinitText.getText();
            String lname = LnameText.getText();
            Integer ssn = Integer.parseInt(SsnText.getText());
            Date bdate = BdateText.getDate();
            String address = AddressText.getText();
            Integer sexId = SexCombo.getSelectedIndex();
            Integer salary = Integer.parseInt(SalaryText.getText());
            String super_ssn = Super_ssnText.getText();
            Integer dno = Integer.parseInt(DnoText.getText());
            String sex;
            if( SalaryText.getText().isEmpty()){
            super_ssn = "NULL";
            }
            if( sexId==0){
             sex = "M";
            }else{
              sex = "F";
         }
  
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3308/office?useSSL=false","root","");
            insert = con.prepareStatement("UPDATE employee SET Fname= ?,Minit= ?,Lname= ?,Bdate=?,Address=?,Sex=?,Salary=?,Super_ssn=?,Dno=? WHERE Ssn= ?");
            insert.setString(1, fname);
            insert.setString(2, minit);
            insert.setString(3, lname);
            java.util.Date dt = bdate;
            java.sql.Date bdt = new java.sql.Date(dt.getTime());
            insert.setDate(4, bdt);
            insert.setString(5, address);
            insert.setString(6, sex);
            insert.setInt(7, salary);
            insert.setString(8, super_ssn);
            insert.setInt(9, dno);
            insert.setInt(10, ssn);
            
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Updated");
            //clear the text boxes
            FnameText.setText("");
            MinitText.setText("");
            LnameText.setText("");
            SsnText.setText("");
            BdateText.setDate(null);
            AddressText.setText("");
            SexCombo.setSelectedItem(null);
            SalaryText.setText("");
            Super_ssnText.setText("");
            DnoText.setText("");
            update_data();
           
            
        } catch (ClassNotFoundException ex) {
           
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DnoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DnoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DnoTextActionPerformed

    private void Super_ssnTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Super_ssnTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Super_ssnTextActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        try {   
                
            Integer ssn = Integer.parseInt(SsnText.getText());
            int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure you want to Delete this record?","Danger",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3308/office?useSSL=false","root","");
            insert = con.prepareStatement("DELETE FROM employee WHERE Ssn = ?");
            
            insert.setInt(1,ssn);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Deleted");
            
            //clear the text boxes
            FnameText.setText("");
            MinitText.setText("");
            LnameText.setText("");
            SsnText.setText("");
            BdateText.setDate(null);
            AddressText.setText("");
            SexCombo.setSelectedItem(null);
            SalaryText.setText("");
            Super_ssnText.setText("");
            DnoText.setText("");

            update_data();
           
           }

        } catch (ClassNotFoundException ex) {
        
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel click = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();

        FnameText.setText(click.getValueAt(selectedIndex, 0).toString());
        MinitText.setText(click.getValueAt(selectedIndex, 1).toString());
        LnameText.setText(click.getValueAt(selectedIndex, 2).toString());
        SsnText.setText(click.getValueAt(selectedIndex, 3).toString());
        String dt  = click.getValueAt(selectedIndex, 4).toString();
        java.util.Date date = null;
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse(dt);
        } catch (ParseException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        BdateText.setDate(date);
        AddressText.setText(click.getValueAt(selectedIndex, 5).toString());
        if(click.getValueAt(selectedIndex, 6).toString() == "M"){
            SexCombo.setSelectedIndex(0);
        }else{
            SexCombo.setSelectedIndex(1);
        }
        
        SalaryText.setText(click.getValueAt(selectedIndex, 7).toString());
        Super_ssnText.setText(click.getValueAt(selectedIndex, 8).toString());
        DnoText.setText(click.getValueAt(selectedIndex, 9).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void SexComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SexComboActionPerformed

    private void MinitTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinitTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinitTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel Address;
    private javax.swing.JTextField AddressText;
    private javax.swing.JLabel Bdate;
    private com.toedter.calendar.JDateChooser BdateText;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel Dno;
    private javax.swing.JTextField DnoText;
    private javax.swing.JLabel Fname;
    private javax.swing.JTextField FnameText;
    private javax.swing.JLabel Lname;
    private javax.swing.JTextField LnameText;
    private javax.swing.JLabel Minit;
    private javax.swing.JTextField MinitText;
    private javax.swing.JLabel Salary;
    private javax.swing.JTextField SalaryText;
    private javax.swing.JLabel Sex;
    private javax.swing.JComboBox<String> SexCombo;
    private javax.swing.JLabel Ssn;
    private javax.swing.JTextField SsnText;
    private javax.swing.JLabel Super_ssn;
    private javax.swing.JTextField Super_ssnText;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
